### ISSUE TITLE
This editor cannot detect the game process

### ISSUE THREAD

**Issue by dongfangxiyu** [crazydoomy/MD-Replay-Editor#5]
After the update upon July, the editor cannot detect the game process, the error dialogue box notes that "the game is not running"

**Comment by crazydoomy** [comment]
everything seems to be working fine for me, so I'm not sure what the issue is

do you mind telling me what OS you are using?

**Comment by dongfangxiyu** [comment]
It turns out that I didn't run it with administrator rights. Everything is fine now. Thanks for your reply.
